export { default as About } from "./about"
export { default as Blog } from "./blog"
export { default as Contact } from "./contact"
export { default as Header } from "./header"
export { default as Pricing } from "./pricing"
export { default as Work } from "./work"
